### ISSUE TITLE
Add end-to-end test for "validate" subcommand

### ISSUE THREAD

**Issue by nstogner** [GoogleCloudPlatform/terraform-validator#10]
Strategy: vendor a policies dir (see: https://github.com/forseti-security/policy-library) and run `terraform-validator validate --output-json ...` against it, asserting on expected violations.

**Comment by yukinying** [comment]
This is implemented in https://github.com/GoogleCloudPlatform/terraform-validator/blob/3cdd6e984bb99bf6db7e87d58222ffe96379fe74/test/cli_test.go#L116
