### ISSUE TITLE
Lift resource conversion into upstream library

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/terraform-validator#103]
Currently, adding support for new resources is a two-step process:
1. Updating the conversion library to add support for the resource
2. Updating the terraform-validator repo to support the resource, including adding it to [mappers](https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/converters/google/mappers.go#L46) and adding appropriate [test data](https://github.com/GoogleCloudPlatform/terraform-validator/tree/master/testdata/templates).

We would like to consolidate this so new resource additions/changes can happen solely in the conversion library. This would likely include:
1. Moving mappers into the conversion library
2. Moving test data into the conversion library (the test execution could likely still happen in this repo, but the data itself should be upstreamed).

**Comment by melinath** [comment]
Closing this issue; we're going to go with a different strategy.
