### ISSUE TITLE
Resource ancestry lookup will fail for to-be-created projects

### ISSUE THREAD

**Issue by nstogner** [GoogleCloudPlatform/terraform-validator#11]
If a plan contains a `google_project` that has not yet been created and there are other resources to be created under that project in the plan all of the resource's will fail on an ancestry lookup.

**Comment by AdrienWalkowiak** [comment]
Is it still true?

I have done some testing with the latest code and it seems to be working fine in this specific case.

**Comment by morgante** [comment]
I think we worked around this by using the provider project, leading to #50.
