### ISSUE TITLE
Child_modules are nested, and only the first level is parsed

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/terraform-validator#110]
Per https://www.terraform.io/docs/internals/json-format.html#plan-representation
```
    "child_modules": [
      // Each entry in "child_modules" has the same structure as the root_module
      // object, with the additional "address" property shown below.
      {
        // [Other fields omitted] 
       
        // Each module object can optionally have its own
        // nested "child_modules", recursively describing the
        // full module tree.
        "child_modules": [ ... ],
      }
```

However, https://github.com/GoogleCloudPlatform/terraform-validator/blob/0c219acc485d54b2a62537bdd4072d678fbe33d8/tfplan/json_plan.go#L27-L36 indicated that only the first level of child modules are parsed. This seems to be problematic as nested child modules are very common in Terraform configurations.

**Comment by yukinying** [comment]
And it looks like the child module parsing is done in https://github.com/GoogleCloudPlatform/terraform-validator/blob/0c219acc485d54b2a62537bdd4072d678fbe33d8/tfplan/json_plan.go#L182-L188

**Comment by morgante** [comment]
Good catch, thank you! This is definitely a big issue and we should probably add some tests to ensure it's addressed.
