### ISSUE TITLE
Issues with deploying google_project resource

### ISSUE THREAD

**Issue by agosto-lorinronken** [GoogleCloudPlatform/terraform-validator#112]
We are encountering an issue with deploying the `google_project` resource in our pipelines.  The error we encounter is as follows:

`Error: converting tfplan to CAI assets: converting resource google_project: augmenting asset: project: required field is not set`

I understand that generally there would be nothing this resource could violate by itself however for our CI/CD pipelines there will be times when users will simply be deploying just a single project (or folder).  Is there currently a way for us to bypass the project field when the TFPlan only contains the `google_project` or `google_folder` resource?  

I apologize ahead of time if this has already been addressed I just was unable to find anything in my searches.

Google Project TF: https://www.terraform.io/docs/providers/google/r/google_project.html
Google Folder TF: https://www.terraform.io/docs/providers/google/r/google_folder.html

**Comment by morgante** [comment]
Could you share the Terraform config you're trying to validate?

We definitely want to support this.

**Comment by agosto-lorinronken** [comment]
Absolutely, I was just testing something simple to start:

Main.tf:
```
provider "google" {
}

resource "google_project" "my_project" {
  name       = "test-prod-33221"
  project_id = "test-prod-33221"
  org_id     = "${var.ORG_ID}"
}
```
As a side note there is also a backend.tf file that defines state file location and an environment variable used for the credentials.  

I also have tried the following to verify the folder resource as well:
```
provider "google" {
}

resource "google_folder" "engineering" {
  display_name = "engineering"
  parent       = "organizations/1027198805420"
}

resource "google_project" "my_project" {
  name       = "test-prod-33221"
  project_id = "test-prod-33221"
  folder_id  = google_folder.engineering.name
}
```

The second one fails with the same error message as seen below:
`Error: converting tfplan to CAI assets: converting resource google_project: augmenting asset: project: required field is not set`

**Comment by agosto-lorinronken** [comment]
Wanted to add to this as I just tested creating only the folder and everything works as expected.  This appears to only be an issue with the `google_project` resource.

**Comment by yukinying** [comment]
Did you use the latest version (Nov 16th) of terraform-validator? The `project_id` field is considered as `project` in `google_project` configuration. 

Code: https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/vendor/github.com/GoogleCloudPlatform/terraform-google-conversion/google/project.go#L14 

Original commit in upstream repository: https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/246

**Comment by agosto-lorinronken** [comment]
Originally I used the latest binary thats in GCS found at `gs://terraform-validator/releases/2019-11-07/terraform-validator-<version>` but after encountering errors with that I pulled the master branch from this repository and compiled a local version of the binary using `make releases`.  Unfortunately even with that build of the binary I encountered this same issue.

**Comment by morgante** [comment]
I was able to reproduce this on `master` when I *don't* set an explicit fallback project on the command line:

```
../bin/terraform-validator convert terraform.tfplan.json --verbose
```

@agosto-lorinronken As a temporary fix, you can specific a fallback project ID (this is just used for resource hierarchy lookups):

```
../bin/terraform-validator convert terraform.tfplan.json --project some-project 
```

I'm working on a more permanent fix.

**Comment by xingao267** [comment]
Can we cut a release to include this fix?

**Comment by morgante** [comment]
Sure, I just cut a new release.
