### ISSUE TITLE
Error: converting tfplan to CAI assets: .. Error resolving image name ''"

### ISSUE THREAD

**Issue by acmck** [GoogleCloudPlatform/terraform-validator#113]
**What do I see?**
When running a policy validate on our terraform, we get the following error.

`Error: converting tfplan to CAI assets: converting resource google_compute_disk: converting asset: Error resolving image name '': Error checking if image exists: json: invalid use of ,string struct tag, trying to unmarshal "projects/acmck-02-sandbox/global/images/" into uint64`

**What do I expect**
The policy validation  to output a violation(s) or report "No Violations".

**Reproduce**
Attach a disk to GCE instance with no image defined

```
resource "google_compute_disk" "bastion-disk" {
  name = "${var.name}-disk"
  type = "pd-ssd"
  zone = "us-central1-a"
  size = 100
}
```

and attach inside the instance resource:

```
    attached_disk {
      source      = google_compute_disk.bastion-disk.self_link
  }
```

**versions**

```
bash-5.0# terraform version
Terraform v0.12.16
+ provider.google v2.17.0
+ provider.google-beta v2.20.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
+ provider.random v2.2.1

Your version of Terraform is out of date! The latest version
is 0.12.17. You can update by downloading from https://www.terraform.io/downloads.html

bash-5.0# terraform-validator version
Build version: 2019-11-07
```
Happens on alpine or debain base image based containers.

```
bash-5.0# uname -a
Linux 9a1661522e53 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 Linux
```

**Comment by morgante** [comment]
I've verified this, looks like we don't properly support empty disks. Working on a fix.

**Comment by morgante** [comment]
@danawillow It looks like we're autogenerating the [image disk resolver](https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/compute_disk.go#L322) for conversion. Any idea why it would be failing, even though Terraform itself is fine with the empty disk? It looks like the provider code is [identical](https://github.com/terraform-providers/terraform-provider-google/blob/a391fe5f9ee79c8c9927015cff01b847e63366ca/google/image.go#L86).

**Comment by danawillow** [comment]
Terraform is fine with the empty disk because `d.GetOk` will return false if the field is empty, so we skip that block. What does the validator do in that case?

**Comment by TJarriault** [comment]
hi,
i've got a similar issue.
Terraform : v0.12.29
Terraform-validator-linux-amd64 : 2020-09-24

i generate the output of the tfplan.tfplan with the command line : terraform plan -out tfplan.tfplan
and terraform show -json tfplan.tfplan  > tfplan.tfplanNEW

./terraform-validator-linux-amd64 validate tfplan.tfplanNEW   --policy-path policies/templates --verbose
Error: converting tfplan to CAI assets: Terraform 0.12 support plans only in JSON format, got: .tfplanNEW

os : Linux ip-10-215-10-183 4.4.0-1111-aws #123-Ubuntu SMP Sat Jul 4 02:03:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

any idea ?

Regards

**Comment by danawillow** [comment]
if I had to guess, I'd say that the issue is that the plan shouldn't have the suffix .tfplanNEW. Have you tried naming it something else that just ends with .tfplan?

**Comment by Jberlinsky** [comment]
@melinath IHAC who's running into this as part of rolling out `terraform-validator` -- any chance it could get a quick look? :)

**Comment by melinath** [comment]
@Jberlinsky If you're working with a dedicated Technical Account Manager / Customer Engineer: to expedite the investigation and resolution of this issue, please refer to these instructions: https://github.com/hashicorp/terraform-provider-google/wiki/Customer-Contact#raising-gcp-internal-issues-with-the-provider-development-team

**Comment by Jberlinsky** [comment]
Filed https://github.com/GoogleCloudPlatform/terraform-google-conversion/issues/764 upstream. Working on getting an escalation ticket filed by the account team.

**Comment by Jberlinsky** [comment]
Moving contents of ____ here:

When I merge https://github.com/GoogleCloudPlatform/terraform-validator/pull/119 into `terraform-validator`'s `main` branch and run its tests, I receive the following stack trace:

```
--- FAIL: TestReadPlannedAssetsCoverage (0.02s)
    --- FAIL: TestReadPlannedAssetsCoverage/example_compute_disk_empty (0.02s)
panic: nil context [recovered]
	panic: nil context

goroutine 57 [running]:
testing.tRunner.func1.2(0x403f400, 0x4d93e90)
	/usr/local/Cellar/go/1.16.6/libexec/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000288f00)
	/usr/local/Cellar/go/1.16.6/libexec/src/testing/testing.go:1146 +0x4b6
panic(0x403f400, 0x4d93e90)
	/usr/local/Cellar/go/1.16.6/libexec/src/runtime/panic.go:965 +0x1b9
net/http.(*Request).WithContext(...)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/request.go:356
golang.org/x/net/context/ctxhttp.Do(0x0, 0x0, 0x636b720, 0xc000140400, 0x406b560, 0x1, 0xc0021a8580)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/net@v0.0.0-20210503060351-7fd8e65b6420/context/ctxhttp/ctxhttp.go:27 +0x34f
golang.org/x/oauth2/internal.doTokenRoundTrip(0x0, 0x0, 0xc000140400, 0x48, 0xc0001dbdd0, 0x18)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/internal/token.go:232 +0x7b
golang.org/x/oauth2/internal.RetrieveToken(0x0, 0x0, 0xc0007227d0, 0x48, 0xc0001dbdd0, 0x18, 0x484c1d7, 0x23, 0xc002110690, 0x1, ...)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/internal/token.go:202 +0xe9
golang.org/x/oauth2.retrieveToken(0x0, 0x0, 0xc000310690, 0xc002110690, 0xc002110760, 0x403f400, 0xc002110698)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/token.go:157 +0x92
golang.org/x/oauth2.(*tokenRefresher).Token(0xc001e9fad0, 0x100f93b, 0x8, 0x203000)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/oauth2.go:270 +0x1e5
golang.org/x/oauth2.(*reuseTokenSource).Token(0xc000dfb6c0, 0x0, 0x0, 0x0)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/oauth2.go:304 +0xaf
golang.org/x/oauth2.(*Transport).RoundTrip(0xc000dfb700, 0xc000140100, 0x0, 0x0, 0x0)
	/Users/berlinsky/src/go/pkg/mod/golang.org/x/oauth2@v0.0.0-20210427180440-81ed05c6b58c/transport.go:45 +0x9e
net/http.send(0xc000140100, 0x4de4b60, 0xc000dfb700, 0x0, 0x0, 0x0, 0xc0006e2f60, 0xc002110be8, 0x1, 0x0)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc001e9fb60, 0xc000140100, 0x0, 0x0, 0x0, 0xc0006e2f60, 0x0, 0x1, 0x0)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc001e9fb60, 0xc000140100, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	/usr/local/Cellar/go/1.16.6/libexec/src/net/http/client.go:585
google.golang.org/api/internal/gensupport.SendRequest(0x0, 0x0, 0xc001e9fb60, 0xc000140100, 0xc002110f78, 0x55, 0x0)
	/Users/berlinsky/src/go/pkg/mod/google.golang.org/api@v0.46.0/internal/gensupport/send.go:26 +0xd0
google.golang.org/api/compute/v1.(*ImagesGetFromFamilyCall).doRequest(0xc0021110e8, 0x47ebfa7, 0x4, 0x0, 0x1010098, 0x30)
	/Users/berlinsky/src/go/pkg/mod/google.golang.org/api@v0.46.0/compute/v1/compute-gen.go:74226 +0x809
google.golang.org/api/compute/v1.(*ImagesGetFromFamilyCall).Do(0xc0021110e8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/berlinsky/src/go/pkg/mod/google.golang.org/api@v0.46.0/compute/v1/compute-gen.go:74238 +0xa5
github.com/GoogleCloudPlatform/terraform-google-conversion/google.resolveImageFamilyExists(0xc00030f200, 0x47ee6c1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/berlinsky/src/clients/google/usb/terraform-google-conversion/google/image.go:63 +0x10a
github.com/GoogleCloudPlatform/terraform-google-conversion/google.resolveImage(0xc00030f200, 0x47ee6c1, 0x6, 0x0, 0x0, 0x0, 0x0, 0x9, 0xc0007f0d00, 0x34, ...)
	/Users/berlinsky/src/clients/google/usb/terraform-google-conversion/google/image.go:189 +0x17d2
github.com/GoogleCloudPlatform/terraform-google-conversion/google.resourceComputeDiskEncoder(0x4e81758, 0xc002031ad0, 0x47a3780, 0xc00030f200, 0xc002031b90, 0x1, 0x0, 0x0)
	/Users/berlinsky/src/clients/google/usb/terraform-google-conversion/google/compute_disk.go:373 +0x5b4
```

It appears that we reach [google/image.go line 48](https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/image.go#L48), which attempts to make a request containing an empty string `name`, which leads to a `panic`.

I'm not familiar with how modular-magician generates this file, so I'm afraid my debugging might cease to be useful beyond this point.

**Comment by Jberlinsky** [comment]
This appears to be an error in the implementation of [FakeResourceData.GetOk](https://github.com/GoogleCloudPlatform/terraform-validator/blob/f299671d7ef7042d28ac0bd863169b40a885ec2c/converters/google/fake_resource_data.go#L54). When I add the following test case, I receive test failures, which are not expected:

```
func TestFakeResourceData_getOkNotOkStrVal(t *testing.T) {
	p := provider.Provider()

	values := map[string]interface{}{
		"name":  "test-disk",
		"type":  "pd-ssd",
		"zone":  "us-central1-a",
		"physical_block_size_bytes": 4096,
	}
	d := NewFakeResourceData(
		"google_compute_disk",
		p.ResourcesMap["google_compute_disk"].Schema,
		values,
	)
	res, ok := d.GetOk("image")
	assert.Nil(t, res)
	assert.False(t, ok)
}
```

```
--- FAIL: TestFakeResourceData_getOkNotOkStrVal (0.00s)
    fake_resource_data_test.go:136:
        	Error Trace:	fake_resource_data_test.go:136
        	Error:      	Expected nil, but got: ""
        	Test:       	TestFakeResourceData_getOkNotOkStrVal
```
