### ISSUE TITLE
Support Terraform 0.12 plan output

### ISSUE THREAD

**Issue by nstogner** [GoogleCloudPlatform/terraform-validator#12]
See: https://github.com/hashicorp/terraform/issues/20155

**Comment by kojnp** [comment]
Is this why I get "Error: converting tfplan to CAI assets: reading terraform plan: not a valid plan file" ?
terraform -v
Terraform v0.12.2
What Terraform version should I be using?
thanks

**Comment by kojnp** [comment]
works with 0.11
got this one  https://releases.hashicorp.com/terraform/0.11.6/terraform_0.11.6_linux_amd64.zip
Good enough for me.

**Comment by morgante** [comment]
Yeah, currently only Terraform 0.11 works.

**Comment by jdyke** [comment]
Is there an ETA for this update?

**Comment by morgante** [comment]
We hope to have it available by the end of July.

**Comment by morgante** [comment]
@kopachevsky Please be sure to leverage the 0.12 output format for this: https://www.terraform.io/docs/internals/json-format.html
