### ISSUE TITLE
Document minimum set of permissions needed by Terraform Validator on resources.

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/terraform-validator#124]
Right now there seems no documentation around what permissions on different resources are needed by the Terraform Validator to perform checks. I just got a generic error if I don't have certain permissions to that project.

Error: converting tfplan to CAI assets: converting resource google_compute_instance: augmenting asset: getting resource ancestry: project test-project: googleapi: Error 403: The caller does not have permission

**Comment by morgante** [comment]
You will need Project Viewer access at a minimum.

**Comment by xingao267** [comment]
Is there additional resource specific permissions for https://github.com/GoogleCloudPlatform/terraform-validator#resources?

**Comment by morgante** [comment]
Some might require it, but that shouldn't be the norm and we don't have concrete documentation (or an easy way to maintain/list it).

FYI offline mode shouldn't require any access at all.

**Comment by xingao267** [comment]
@morgante how do I use offline mode? I couldn't find any documentation around that.

**Comment by morgante** [comment]
It's just a flag provided, `--help` should provide some info.

**Comment by xingao267** [comment]
Here is what I got with `--help`

```
$ ./terraform-validator-linux-amd64 version
Build version: 2020-01-23
$ ./terraform-validator-linux-amd64 --help
Validate terraform plans by converting terraform resources to their Google CAI 
(Cloud Asset Inventory) format and passing them through Forseti Config Validator.

Supported Terraform versions = [0.12]

Usage:
  terraform-validator [command]

Available Commands:
  convert                  Convert resources in a Terraform plan to their Google CAI representation.
  help                     Help about any command
  list-supported-resources List supported terraform resources.
  validate                 Validate resources in a Terraform plan by calling Forseti Config Validator.
  version                  Display Terraform Validator version.

Flags:
  -h, --help      help for terraform-validator
      --verbose   Log output to stderr

Use "terraform-validator [command] --help" for more information about a command.
```

**Comment by morgante** [comment]
It's on the `validate` command help. Also info here: https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/cmd/root.go#L39

**Comment by dataplex** [comment]
Any updates on this? It's 2 years later and still a problem. And the code link @morgante gave doesn't point to any kind of offline mode flag.

**Comment by melinath** [comment]
The permissions required are documented here: https://cloud.google.com/docs/terraform/policy-validation/quickstart#before_you_begin

However, it would be worthwhile to document at https://cloud.google.com/docs/terraform/policy-validation/create-cai-constraints as well.
