### ISSUE TITLE
Add support for google_project_service resources

### ISSUE THREAD

**Issue by AdrienWalkowiak** [GoogleCloudPlatform/terraform-validator#126]
Add support forgoogle_project_serive resources in Terraform-Validator. This is needed to use [policies like this](https://github.com/forseti-security/policy-library/blob/449eb95d089e93d40127cfe5d69570010f0af9a2/policies/templates/gcp_serviceusage_allowed_services_v1.yaml)

**Comment by daniel-cit** [comment]
`google_project_service` is supported since release `2021-03-05`
