### ISSUE TITLE
Add support for google_service_account

### ISSUE THREAD

**Issue by zhangran1** [GoogleCloudPlatform/terraform-validator#1290]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description
Terraform vet does not yet supported for the resource google_service_account. Support of those resources can be very beneficial to create policy to block service account creation. 

```
[google_service_account.test-service-account-1: resource type cannot be converted for CAI-based policies: google_service_account. For details, see https://cloud.google.com/docs/terraform/policy-validation/create-cai-constraints#supported_resources]
```

### New or Affected Resource(s)

* google_service_account

### Resource converter exists?

- google_service_account is not supported by a converter

**Comment by vannicktrinquier** [comment]
Planning to work on it

**Comment by vannicktrinquier** [comment]
@zhangran1 service_account change have been merged to magic-modules and terraform-validator

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/magic-modules/pull/7146
