### ISSUE TITLE
Error on gcpGCPBigQueryTableRetentionConstraintV1 with the latest policy-library

### ISSUE THREAD

**Issue by dooman87** [GoogleCloudPlatform/terraform-validator#130]
Hi there,

Not sure whether it should be here or in policy-library, but when I'm running `terraform-validator` I'm getting these errors:

```
templates.templates.gcpGCPBigQueryTableRetentionConstraintV1:59: rego_unsafe_var_error: expression is unsafe
templates.templates.gcpGCPBigQueryTableRetentionConstraintV1:61: rego_unsafe_var_error: expression is unsafe
templates.templates.gcpGCPBigQueryTableRetentionConstraintV1:63: rego_unsafe_var_error: expression is unsafe
templates.templates.gcpGCPBigQueryTableRetentionConstraintV1:70: rego_unsafe_var_error: expression is unsafe
templates.templates.gcpGCPBigQueryTableRetentionConstraintV1:79: rego_unsafe_var_error: expression is unsafe
templates.templates.gcpGCPBigQueryTableRetentionConstraintV1:79: rego_unsafe_var_error: expression is unsafe
templates.templates.gcpGCPBigQueryTableRetentionConstraintV1:81: rego_unsafe_var_error: expression is unsafe
```

If I remove `policies/templates/gcp_bigquery_table_retention_v1.yaml` then error goes away.

**Comment by morgante** [comment]
Apologies for the issue, I wonder if this is related to a new version of OPA having different behavior - see #123

**Comment by dooman87** [comment]
Thanks for the update @morgante. When do you plan to release a new version?

**Comment by morgante** [comment]
@dooman87 If you pull the latest policy-library, I believe this should be resolved.

**Comment by melinath** [comment]
Per previous comment, marking this as resolved. If you're still experiencing the problem please open a new issue :-)
