### ISSUE TITLE
Converting bucket fails when project doesn't exist

### ISSUE THREAD

**Issue by dooman87** [GoogleCloudPlatform/terraform-validator#132]
So, I have a terraform plan that creates a project and a bucket. Before doing `terraform apply` I run `terraform show` and then `terraform-validator validate`. That is failing with:

```
Step #3: Error: converting tfplan to CAI assets: converting resource google_storage_bucket: augmenting asset: getting resource ancestry: project test-project-a0fb: googleapi: Error 403: The caller does not have permission
Step #3: Usage:
Step #3:   terraform-validator validate <tfplan> [flags]
Step #3: 
Step #3: Flags:
Step #3:       --ancestry string      Override the ancestry location of the project when validating resources
Step #3:   -h, --help                 help for validate
ERROR: (gcloud.builds.submit) build 3914438d-f983-44b3-8512-35395ce7464a completed with status "FAILURE"
Step #3:       --offline              Do not connect to GCP API
Step #3:       --output-json          Print violations as JSON
Step #3:       --policy-path string   Path to directory containing validation policies
Step #3:       --project string       Provider project override (override the default project configuration assigned to the google terraform provider when validating resources)
Step #3: 
Step #3: Global Flags:
Step #3:       --verbose   Log output to stderr
Step #3: 
```

The project in the error (test-project-a0fb) doesn't exist yet.

**Comment by dooman87** [comment]
I think I figured out what's happening.

We are using [terraform-google-project-factory](https://github.com/terraform-google-modules/terraform-google-project-factory) to create project and also storing our tfstate in GCS bucket. When 1st time we run `terraform plan` then `project_id` is unknown (we could see `(known after apply)`)  and `terraform-validator` works just fine. However when we run it the second time then `project_id` already has value (cause `random_project_id_suffix` been created) and `terraform-validator` is trying to fetch the project that doesn't exist.

Not sure if it's even possible to solve this issue. I think maybe documentation around fetching resources ancestry would be the best we can do? What do you think @morgante ?

**Comment by morgante** [comment]
Can you share the offending plan?

Once the project is created (and project ID is known), it *should* work fine.

**Comment by dooman87** [comment]
Sorry for silence. I'll try to make a small reproducible example and then attach plan (can't share the original one).

However, worth to mention that the project is not created yet. So, our pipeline (we use cloudbuild) looks like:
`terraform plan` -> `terraform show` -> `terraform-validator` -> `terraform apply`.

So, in our terraform we have project and the bucket. So, when we run our code through pipeline neither is created. And it runs fine with legit failure on `terraform-validator` step (let's say bucket is public and we have that policy turned on). 

The second time when we run the pipeline `terraform-validator` fails on resource conversion because project is not created yet. And that's due to my previous comment regarding `google-project-factory` module and random suffixes used for project id.

Sorry, if above is confusing. I'm going to create a reproducible example with simple pipeline to demo.

**Comment by marktru** [comment]
Internal issue: [b/211887136](b/211887136)

**Comment by melinath** [comment]
I think this should now be resolved by our improved handling of unknown ancestries. Please let me know otherwise.
