### ISSUE TITLE
Issue with Validator on Project / Bucket Creation

### ISSUE THREAD

**Issue by agosto-lorinronken** [GoogleCloudPlatform/terraform-validator#135]
Hello,

We are getting a strange issue that appears to be permission based when we are attempting to create a project/bucket.  The service account we are using has the necessary permissions to create both the project and the bucket and we have confirmed that by temporarily removing the policy-validator step from our pipeline.  However, when we run the `plan.json` through validator we get the following:

_converting tfplan to CAI assets: converting resource google_storage_bucket: augmenting asset: getting resource ancestry: project <project-id>: googleapi: Error 403: The caller does not have permission_

Is there anything specific I should be looking for to address this?  These are the steps we are taking:

- Create TF Plan
- Convert Plan to json
- Run the following: `    terraform-validator validate /workspace/$SHORT_SHA-plan.json --policy-path=/workspace/<path-to-policies>`

Thanks for the help and please let me know if there is anything additional you need to help troubleshoot.

**Comment by morgante** [comment]
Does your Terraform config include creating the project and the bucket in the same execution? Unfortunately that's not currently supported.

You should be able to work around this using the `--offline` and `--ancestry` flags.

**Comment by agosto-lorinronken** [comment]
Morgante,

Yeah that is exactly what we are trying to do.  Thanks for the update -- we will look into using the recommended flags or just pushing two separate Terraform executions.

Thanks!

**Comment by mesuttekin** [comment]
Hi,
I have faced the same problem but I'm only creating a storage bucket. Do you have any idea how I can fix it?

**Comment by morgante** [comment]
@mesuttekin Please share the Terraform plan you're attempting to validate.

**Comment by mesuttekin** [comment]
@morgante I found the problem. The project id was wrong. Thanks anyway
