### ISSUE TITLE
Ancestry path is incorrect

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/terraform-validator#141]
As discussed in https://github.com/forseti-security/policy-library/issues/354, the ancestry path seems to be using project ID instead of project number. This conflicts with expectations and breaks policies.

**Comment by xingao267** [comment]
Just curious. I found project number is used in Policy Library constraints, forseti composite_root_resources and other places instead of project ID. Is the main reason for that is because CAI data for project is based on project number instead of ID?

**Comment by morgante** [comment]
Yes, we use CAI data as the source-of-truth for constraints and that's what we're *meant* to be using everywhere. It looks like Terraform Validator is incorrectly injecting the project ID though.

**Comment by xingao267** [comment]
It looks in Terraform's world, they are using the Project ID to identify projects instead of project number. So what you get directly from a plan or state will likely to be the ID.

**Comment by morgante** [comment]
Yes. we're meant to be converting from ID to number.

**Comment by ralsu091** [comment]
Can I get some clarification? Are we supposed to use something like `organization/123/folder/456/project/789` or `organization/123/folder/456/project/<projectID>` to get Forseti, Config Validator, and Terraform-Validator working.
We currently using `organization/123/folder/456/project/<projectID>`  but we are facing issues when running terraform-validator in our CI pipline. It's reporting resources in a project that we are excluding.

Thanks

**Comment by melinath** [comment]
Closing as duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/182

**Comment by melinath** [comment]
@ralsu091 this should be fixed in newer versions of terraform-validator - please open a new ticket if you're still having issues!
