### ISSUE TITLE
Error ``` invalid nested repetition operator: `**```` 

### ISSUE THREAD

**Issue by Parasdogra** [GoogleCloudPlatform/terraform-validator#146]
Getting below error when trying to trying to validate. Any insights? 
Error: validating: FCV: auditing: core.dependencies.audit:25: eval_builtin_error: re_match: error parsing regexp: invalid nested repetition operator: `**`

**Comment by morgante** [comment]
This looks like an error in your policy library. Can you try using the same library with [CFT Scorecard](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/cli/docs/scorecard.md)?

**Comment by Parasdogra** [comment]
It works for CFT scorecard. However using terraform validator, I get the same error.

**Comment by morgante** [comment]
Can you share which policies you're using?

**Comment by Parasdogra** [comment]
yes sure. I am using these sample policies.
https://github.com/forseti-security/policy-library/tree/master/samples

**Comment by Parasdogra** [comment]
Any updates?
