### ISSUE TITLE
how to implement support for additional resource types?

### ISSUE THREAD

**Issue by alan-young** [GoogleCloudPlatform/terraform-validator#155]
Hi,

I'm trying to understand how additional CAI resource types get implemented in terraform-validator.

I'm looking at converters/google/mappers.go: 
_func mappers() map[string][]mapper {
	return map[string][]mapper{_

which maps terraform resource types to the corresponding converter pulled from _github.com/GoogleCloudPlatform/terraform-google-conversion/google_

Apart from adding the corresponding entry into the map being returned from mappers(), what else do I need to consider?

Thanks

**Comment by morgante** [comment]
Thanks for your interest!

Adding new resources is a two-step process:

1. Add support for the resource to the [conversion repo](https://github.com/GoogleCloudPlatform/terraform-google-conversion) if it's not already there. This is done by contributing to the magic modules repo, especially in the case of hand-written resources. ([sample PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/2564)
2. Add support to validator by adjusting [mappers](https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/converters/google/mappers.go#L46) and adding [new test cases](https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/test/cli_test.go#L53).

**Comment by alan-young** [comment]
Thanks @morgante

**Comment by alan-young** [comment]
Thanks @morgante
