### ISSUE TITLE
Validator and TGC are out of sync with the providers

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/terraform-validator#158]
Magic-modules is the shared source code base for both Terraform-google-conversion and terraform-provider-google.

Terraform-validator and Terraform-google-conversion are out of sync with current the version of terraform-provider-google. The last sync between then was in PR https://github.com/GoogleCloudPlatform/terraform-validator/pull/129 merged in 2020-03-02.

The provider has been evolved this year while Terraform-google-conversion (tgc) and Terraform-validator have not been updated but for:

- A bump in the version of `forseti-security/config-validator`,
- The addition of policy change detection capability,
- Support for Spanner Instance resource,
- some tests fixes.

This lead to some compatibility issues with code generated by the current version of magic-modules.

We have these basic differences between validator/tgc and the provider as of 2020-11-20:

- [x] The Provider uses `go 1.14` while validator and tgc use `go 1.13` https://github.com/GoogleCloudPlatform/terraform-validator/pull/163 https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/598
- [x] The Provider code moved to `github.com/hashicorp/terraform-provider-google` and  then changed its go package to the new location but is still referenced as `github.com/terraform-providers/terraform-provider-google` in validator. Validator code needs changes to be able to use the newest version of the provider https://github.com/GoogleCloudPlatform/terraform-validator/pull/165
- [x] Validator has not acknowledge that the provider current version is v3 not v1 since it is referencing it by a pseudo-version not a by a real tagged version. https://github.com/GoogleCloudPlatform/terraform-validator/pull/165
- [x] The Provider uses `terraform-plugin-sdk` v2 and validator still uses `terraform-plugin-sdk` v1 https://github.com/GoogleCloudPlatform/terraform-validator/pull/165
- [x] The Provider uses `google.golang.org/api v0.34.0`, tgc and validator use `google.golang.org/api v0.16.0` https://github.com/GoogleCloudPlatform/terraform-validator/pull/165
- [X] Vendoring has been removed from the provider but is still in used in tgc https://github.com/GoogleCloudPlatform/terraform-google-conversion/pull/596
- [x] melinath: Vendoring has been removed from the provider and tgc but is still used in validator https://github.com/GoogleCloudPlatform/terraform-validator/pull/159
- [X] The Validator still has "legacy code" for tf v0.11 on the master branch, which conflicts with `terraform-plugin-sdk` v2 regarding the usage of `terraform.Plan` type and other deleted types. https://github.com/GoogleCloudPlatform/terraform-validator/pull/160
- [x] Some tgc usages of generateUserAgentString need to be updated to match the schema changes in https://github.com/GoogleCloudPlatform/magic-modules/pull/4237 (PR: https://github.com/GoogleCloudPlatform/magic-modules/pull/4315)
- [ ] Integration tests are failing https://github.com/GoogleCloudPlatform/terraform-validator/pull/166 https://github.com/GoogleCloudPlatform/terraform-validator/pull/167 https://github.com/GoogleCloudPlatform/magic-modules/pull/4328 https://github.com/GoogleCloudPlatform/terraform-validator/pull/168

**Comment by rileykarson** [comment]
https://github.com/hashicorp/terraform-provider-google/issues/7781, https://github.com/hashicorp/terraform-provider-google/issues/7797 are on track to get assigned in the sprint starting today. They cover updating tgc, but not validator. It doesn't feel unreasonable for us to attempt updating the validator versions as well, but it isn't explicitly part of either issue.

/cc @melinath

**Comment by daniel-cit** [comment]
Another case of resource out of sync is the handwritten `storage_bucket` which is still using `bucket_policy_only` in the conversion and in the policy library :

Related issues:

- https://github.com/GoogleCloudPlatform/terraform-google-conversion/issues/591
- https://github.com/forseti-security/policy-library/issues/388

**Comment by melinath** [comment]
Resolved as of the merge of #168.
