### ISSUE TITLE
Support for current versions of Terraform

### ISSUE THREAD

**Issue by Jake-Mok-Nelson** [GoogleCloudPlatform/terraform-validator#161]
Seems like Terraform Validator doesn't support current versions of Terraform, I was wondering if you had further information on when you'll bring support for TF 14 which is now GA.

**Comment by ericyz** [comment]
Hi @Jake-Mok-Nelson , the Terraform Validator should still work with TF14, because TF14 generates the same json format for terraform plan, which is the only input Terraform Validator depends on.
