### ISSUE TITLE
gcp_storage_bucket_policy_only_v1 does not recognize uniform bucket-level access property

### ISSUE THREAD

**Issue by daniel-cit** [GoogleCloudPlatform/terraform-validator#170]
The validation for `gcp_storage_bucket_policy_only_v1` fails because the rego rule does not look at the uniform bucket-level access property and `terraform-google-conversion` does not maps the property.

The original property `bucket_policy_only` was deprecated. 

Related issues:

- https://github.com/forseti-security/policy-library/issues/388
- https://github.com/GoogleCloudPlatform/terraform-google-conversion/issues/591

**Comment by daniel-cit** [comment]
This issue has been fixed by:

- https://github.com/forseti-security/policy-library/pull/390
- https://github.com/GoogleCloudPlatform/magic-modules/pull/4346
- https://github.com/GoogleCloudPlatform/terraform-validator/pull/171

**Comment by melinath** [comment]
Closing per previous comment. Resolved by https://github.com/GoogleCloudPlatform/terraform-validator/issues/171.
