### ISSUE TITLE
External IP policy fails

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/terraform-validator#19]
The [external IP policy](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_external_ip_access.yaml) fails because the Validator returns a *plurals* for access config instead of singular.

The [API](https://cloud.google.com/compute/docs/reference/rest/v1/instances/insert) and Terraform Validator both expect plural on network intefaces:
```
  "networkInterfaces": [
    {
      "network": string,
      "subnetwork": string,
      "networkIP": string,
      "name": string,
      "accessConfigs": [
        
      ],
      "aliasIpRanges": [
        
      ],
      "fingerprint": string,
      "kind": string
    }
  ],
```

Yet the CAI data has network interface and access config as a singular field:
```
{
      "data": {
        "networkInterface": [
          {
            "accessConfig": [
              {
                "name": "external-nat",
                "networkTier": "PREMIUM",
                "type": "ONE_TO_ONE_NAT"
              }
            ],
      }
    }
  }
```

**Comment by alexsgoogle** [comment]
Link to external IP Policy is broken, is it referring to this? https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_external_ip_access_v1.yaml

**Comment by morgante** [comment]
Yes, due to the naming inconsistency in CAI.

**Comment by yukinying** [comment]
I think this is fixed in the upstream dependencies: https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/66d68e4bb49e24d9c6c4e6d7b0f743ab729f8a39/google/compute_instance.go#L139

Also https://godoc.org/google.golang.org/api/compute/v0.beta#Instance is showing it as `networkInterfaces`.

**Comment by melinath** [comment]
It looks like CAI changed its output to match what is in TFV / API. See https://github.com/GoogleCloudPlatform/policy-library/pull/128 for more details.
