### ISSUE TITLE
Add support for google_compute_subnetwork

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/terraform-validator#20]
~- [ ] google_compute_network~ #211
- [ ] google_compute_subnetwork
- [x] google_compute_firewall

**Comment by mldmld68** [comment]
Hi all,
Please add firewall and constraint sample policies to check

    if an SA can talk to another SA based on a regex on their names
    if TCP 22 or 3389 is opened to 0.0.0.0/0
    if TCP open ports specify a wide range : [1-65535]
    if a range of subnets are the only one allowed for ingress

**Comment by melinath** [comment]
@mldmld68 firewall is now supported
