### ISSUE TITLE
Overriding ancestry discovery

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/terraform-validator#21]
Ancestry discovery (https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/converters/google/convert.go#L220) use Google APIs to retrieve the ancestry path. In scenario that validation could be run in an isolated environment, it would be desirable to provide an option to suppress such behavior. It would be great if the tool can use a flag like --folder (as in --project) such that it can provide the information needed instead of dynamic ancestry discovery.

**Comment by morgante** [comment]
Fixed by #22.
