### ISSUE TITLE
Add support for google_compute_network

### ISSUE THREAD

**Issue by layidavids** [GoogleCloudPlatform/terraform-validator#211]
Hello Guys,

I am new to terraform-validator and I was running some tests with it.

I attempted the following:

 - Creating a default network with "google_compute_network"
 - Assigned a member a serviceAccountUser IAM role
 - Assigning an External IP to a compute instance

Of the 3 tasks, only the last one reported a violation and I keep on getting an error: "unsupported resource: google_compute_network" for the network and no violation was reported for the IAM configuration. 

![image](https://user-images.githubusercontent.com/68163365/113465478-3b42a180-9402-11eb-910e-aea86329a367.png)

![image](https://user-images.githubusercontent.com/68163365/113465499-704ef400-9402-11eb-90f8-81b26205ac65.png)

The config validator scanner was able to report all 3 violations.

**Comment by layidavids** [comment]
Just noticed these are not supported yet. Thanks.

**Comment by melinath** [comment]
@layidavids would you like to open a feature request for us to add support for google_compute_network?

**Comment by aakinsan** [comment]
yes please. thanks.

**Comment by layidavids** [comment]
yes. thanks.
