### ISSUE TITLE
Document usage of --ancestry / --offline options

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#220]
Recently I wanted to direct a user to documentation about the `--ancestry` and `--offline` options and discovered that it is lacking. Since these are critical paths for some users, we should ensure they are well-documented. In particular, they should be covered in:

- [the user guide](https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-terraform-validator)
- probably in [Getting started](https://github.com/GoogleCloudPlatform/terraform-validator/blob/master/docs/getting_started.md)

validateCmd and convertCmd currently require ancestry if offline is set but not vice versa, so the documentation should be clear about what the behavior is in offline vs not-offline mode.

**Comment by marktru** [comment]
Internal issue: [b/211888537](b/211888537)

**Comment by melinath** [comment]
This will not be implemented.
