### ISSUE TITLE
Add support for bigquery

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/terraform-validator#23]
[Magic Modules](https://github.com/GoogleCloudPlatform/magic-modules/blob/2631b59e63a2579dc56e0922389bf1e84beb374a/third_party/terraform/resources/resource_bigquery_dataset.go) has support.

**Comment by melinath** [comment]
Some bigquery support exists now; closing this ticket. We may create new tickets in the future for specific resources.
