### ISSUE TITLE
validation read JSON plan Error - invalid character

### ISSUE THREAD

**Issue by suibinz** [GoogleCloudPlatform/terraform-validator#230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Terraform Validator version

Other versions not tried
gs://terraform-validator/releases/2021-04-15/terraform-validator-linux-amd64
gs://terraform-validator/releases/2021-06-11/terraform-validator-linux-amd64

### Affected Resource(s)

* google_XXXXX
Unsured

### Terraform Plan JSON

```json

```
https://www.dropbox.com/s/ovxjmhyvb9jv8pa/debugplan.out.json.gpg?dl=0

### Debug Output
https://gist.github.com/suibinz/650d287dc9c2c4b7cbdfcc39a61edd96

### Actual Behavior
It seems somewhat env related:
1) GCP cloudbuild is fine;
2) error observed with Github action running "ubuntu-latest"

### Steps to Reproduce

1. `terraform plan -out=plan.out && terraform show -json plan.out > /tmp/plan.out.json`
2. `terraform-validator validate /tmp/plan.out.json --policy-path="/tmp/policy-library" `

### References

* #0000

**Comment by melinath** [comment]
@suibinz Could you please share either your terraform plan JSON or your original configuration? Otherwise there is no way for us to reproduce this issue.

**Comment by suibinz** [comment]
the plan/json is rather large (.5M) for in-line. I am trying to find a way to share.

**Comment by suibinz** [comment]
added shared dropbox link

**Comment by slevenick** [comment]
Hmmm, I'm able to read the json plan just fine on macOS. Not really sure why this wouldn't work on ubuntu-latest. Can you parse a simple json plan with the github action?

Can you share the github action configuration?

**Comment by suibinz** [comment]
Here is the link to a GPG-encrypted plan.out.json that is simply running google bootstrap module.
https://www.dropbox.com/s/ovxjmhyvb9jv8pa/debugplan.out.json.gpg?dl=0

Same error from the validator. (I have seen a few stackoverflow threads discussing UnmarshalJson with similar errors.)

**Comment by slevenick** [comment]
Are you using https://github.com/hashicorp/setup-terraform in the github actions somehow? I see several bugs that claim that turning `terraform_wrapper` off fixes similar issues.

See: https://github.com/gruntwork-io/terratest/issues/706
https://github.com/gruntwork-io/terragrunt/issues/1202

**Comment by suibinz** [comment]
not I wrote my own action:
`jobs:
  lint:
    name: terraform lint
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@master
      - name: Terraform-Lint
        uses: alexnorell/terraform-lint@v1.0.0
  tf-plan-and-validate:
    name: setup terraform-validator and clone org policies
    runs-on: ubuntu-latest
    env:
        GOOGLE_CREDENTIALS: ${{secrets.TF_SA_JSON}}
        GOOGLE_APPLICATION_CREDENTIALS: "/tmp/google.json"
    steps:
      - name: set gcloud env
        run: |
          echo ${{secrets.GCLOUD_AUTH}} > /tmp/google.json && cat /tmp/google.json
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
      - name: gcloud auth
        run: |
          gcloud config set account org-terraform@fndn-seed-21cd.iam.gserviceaccount.com && \
          gcloud auth activate-service-account org-terraform@fndn-seed-21cd.iam.gserviceaccount.com \
          --key-file /tmp/google.json
      - name: gsutil cp validator to root dir
        run: |
          gsutil cp gs://terraform-validator/releases/2021-04-07/terraform-validator-linux-amd64 /tmp/terraform-validator && chmod +x /tmp/terraform-validator
      - name: Clone policy-library
        # TODO fork this library
        run:  cd /tmp && git clone https://github.com/forseti-security/policy-library.git
      - name: Checkout terraform binary code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.8
      - name: terraform plan
        id: plan
        run: |
          terraform init && terraform plan -out=plan.out && terraform show -json plan.out > /tmp/plan.out.json && cat /tmp/plan.out.json
      - name: terraform validate plan
        run: |
          /tmp/terraform-validator validate /tmp/plan.out.json --policy-path="/tmp/policy-library" --verbose`

**Comment by suibinz** [comment]
no. I use:
1) cp the validator from public google bkt
2) "uses: google-github-actions/setup-gcloud@master" for the gcloud related requirements
3) run terraform-validator directly (derived from tf_wrapper.sh from https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/build)

**Comment by slevenick** [comment]
In the yaml you pasted originally I see:
`uses: actions/checkout@v2 - name: Setup Terraform uses: hashicorp/setup-terraform@v1`

Which uses the action I linked. Are you using that prior to running the validator? Can you try turning off the terraform_wrapper during that step?

**Comment by suibinz** [comment]
(I guess, yes) I am running the setup. 
I am not sure what you mean by "turning off the terraform_wrapper". A snippet of my current action:
`- name: Checkout terraform binary code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.8
      - name: terraform plan
        id: plan
        run: |
          terraform init && terraform plan -out=plan.out && terraform show -json plan.out > /tmp/plan.out.json && cat /tmp/plan.out.json
      - name: terraform validate plan
        run: |
          /tmp/terraform-validator validate /tmp/plan.out.json --policy-path="/tmp/policy-library" --verbose
        `

**Comment by slevenick** [comment]
From one of those linked bugs against terragrunt: "Assuming you are using https://github.com/hashicorp/setup-terraform to setup terraform in your github action, you need to configure it with terraform_wrapper: false."

Looks like you want something like:
```
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
```

**Comment by suibinz** [comment]
Yes. "terraform_wrapper: false" fixes the issue.

**Comment by slevenick** [comment]
Great!
