### ISSUE TITLE
Merge terraform-google-conversion and terraform-validator repositories

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#237]
Currently, we have separate terraform-google-conversion and terraform-validator repositories. This is for historical reasons that no longer apply. We would like to combine them so that it is easier for contributors to add support for additional resources; the split is a constant source of confusion. This will also simplify making sure that changes made in Magic Modules don't break terraform-validator; currently, it's easy to make a version of terraform-google-conversion that passes its tests but doesn't work with terraform-validator.

This work should accomplish the following:

- [x] Rename [mmv1/provider/terraform_object_library.rb](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/provider/terraform_object_library.rb) to `terraform_validator.rb` [PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/5014)
- [x] Update [build process](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/.ci/gcb-generate-diffs.yml) to refer to validator instead of google-conversion
- [x] Update build process to generate the code into a subdirectory of terraform-validator and run terraform-validator tests (~including integration tests~) [TFV PR](https://github.com/GoogleCloudPlatform/terraform-validator/pull/331) [MM PR](https://github.com/GoogleCloudPlatform/magic-modules/pull/5349)
- [x] Add a note to terraform-google-conversion to state that it is deprecated. (We can't delete it, at least for now, because older terraform-validator versions depend on it.)
- [x] Update make commands & documentation to reflect the new build process [PR](https://github.com/GoogleCloudPlatform/terraform-validator/pull/333)
- [x] Update issue templates to not reference terraform google conversion [PR](https://github.com/GoogleCloudPlatform/terraform-validator/pull/333)

**Comment by morgante** [comment]
Love this idea. :+1:

**Comment by melinath** [comment]
This part of the process is complete. The follow-up work re: running resource tests upstream is covered by https://github.com/GoogleCloudPlatform/terraform-validator/issues/332

**Comment by marktru** [comment]
Internal issue: b/211890077

**Comment by melinath** [comment]
This has been resolved
