### ISSUE TITLE
Improve error message if --project isn't provided and a resource needs it

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#246]
Right now, if a resource is missing an expected `project` value and no default is set via the `--project` flag, we give an error like:

```
required field 'project' is not set
```

We should expand this error to tell the user how to resolve the issue - for example, let them know that they can resolve the issue by supplying `--project` to provide a default project.

**Comment by krishnaindani** [comment]
@melinath Is this issue open to work? I would like to check if I can work on this.

**Comment by melinath** [comment]
@krishnaindani yeah, you're definitely welcome to work on this!

**Comment by krishnaindani** [comment]
Great. Thanks

**Comment by krishnaindani** [comment]
@melinath I have opened the PR and updated the error message, please let me know if looks good or needs to be updated. Thank you.

**Comment by krishnaindani** [comment]
@melinath Appreciate the opportunity to let me work on this.
