### ISSUE TITLE
Add support for terraform version >= 1.0

### ISSUE THREAD

**Issue by sailaxman** [GoogleCloudPlatform/terraform-validator#247]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

When using terraform version 1.0.1, the validator is failing with error below

`Error: converting tfplan to CAI assets: reading resource changes: reading JSON plan: unsupported state format version: expected "0.1", got "0.2"
Usage:
  terraform-validator validate <tfplan> [flags]
Flags:
      --ancestry string      Override the ancestry location of the project when validating resources
  -h, --help                 help for validate
      --offline              Do not make network requests
      --output-json          Print violations as JSON
      --policy-path string   Path to directory containing validation policies
      --project string       Provider project override (override the default project configuration assigned to the google terraform provider when validating resources)
Global Flags:
      --verbose   Log output to stderr`

### New or Affected Resource(s)

all

### References

Current library for transforming data have support only to 0.1
https://github.com/hashicorp/terraform-json/blob/v0.8.0/state.go#L12

New library has support for both 0.1 and 0.2
https://github.com/hashicorp/terraform-json/blob/v0.12.0/state.go#L12

**Comment by melinath** [comment]
resolved by #249
