### ISSUE TITLE
Allow passing an auth token to `validate` via `GOOGLE_OAUTH_ACCESS_TOKEN` env var

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

For scripting, it can be useful to be able to pass a specific auth token via an env var. This is the same mechanism used by the [terraform-provider-google](https://github.com/hashicorp/terraform-provider-google/blob/6cac4b0d55c5f66eaff6d8366d8f0de1d6e5bc1b/google/provider.go#L1267)

### References

* Possibly related: https://github.com/GoogleCloudPlatform/terraform-validator/issues/250

**Comment by morgante** [comment]
In general, I would recommend using an environment variable (like the `GOOGLE_OAUTH_ACCESS_TOKEN` variable Terraform supports) over command-line flags. (Of course, supporting both is even better.)

**Comment by melinath** [comment]
Ah, yeah, this is probably equivalent to `GOOGLE_OAUTH_ACCESS_TOKEN`. I'll update the ticket title and description. If we want to support both we can in the long run but right now just one is probably plenty & I agree that the matching env var for the terraform provider is a good candidate.

**Comment by melinath** [comment]
🤦 This is a duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/250
