### ISSUE TITLE
Combine online & offline ancestry managers

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

Ancestry management is in /ancestrymanager. Currently, there are two ancestry manager structs: online and offline. The online ancestry manager knows how to fetch project ancestry from the API and store it in a cache by project id or number. The offline ancestry manager can take a single ancestry for a single project; any attempt to get ancestry for other projects will fail.

This prevents us from implementing potential improvements like allowing users to specify more complex hierarchies in offline mode.

We should combine the ancestry managers into a single class that has an `offline` option (default: `false`) and that can take a list of project ids + ancestries to prepopulate the cache, regardless of mode. If the offline option is `true`, the class should refuse to make any API requests, and should return an error if the ancestry is not present in the cache. In other words, the current behavior for each mode should remain the same, apart from offline mode gaining support for multiple projects to cache and the online mode gaining the ability to pre-warm its cache.

#### Excluded work

- This does not include changing the CLI behavior to actually support passing multiple projects to be cached
- This does not include adding support for caching a more complex hierarchy, like folders or organizations, in addition to projects.

**Comment by melinath** [comment]
This would not solve for the case where the set of projects is not known initially.

**Comment by iyabchen** [comment]
Hi @melinath,  I will take this issue as a start.

**Comment by melinath** [comment]
@iyabchen sounds good, let me know if you have any questions!

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/terraform-validator/pull/361
