### ISSUE TITLE
KMS key ring & crypto key use incorrect domain in asset type and asset name

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Terraform Validator version

terraform-validator: v0.4.0

### Affected Resource(s)

* google_kms_crypto_key
* google_kms_key_ring

### Expected Behavior

According to https://cloud.google.com/asset-inventory/docs/supported-asset-types, these KMS resources should have the following asset types:

- cloudkms.googleapis.com/KeyRing
- cloudkms.googleapis.com/CryptoKey

The domain (cloudkms.googleapis.com) should also be used in the canonical asset name. (Note: it's also unclear whether the canonical asset name is correctly formatted but that is out of scope of this ticket.)

### Actual Behavior

The code currently uses the domain `kms.googleapis.com` instead: https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/9b13c676d981af90f533cd9526243355a4199f2a/google/kms_crypto_key.go#L24

### References

* This was discovered while reviewing https://github.com/GoogleCloudPlatform/magic-modules/pull/4997

ref: b/199763427

**Comment by melinath** [comment]
@palani-ram-google-partner is working on a fix for this

**Comment by palani-ram-google-partner** [comment]
@melinath I have worked on this and have a fix ready to go. please assign this to me, so i can make a PR.

**Comment by melinath** [comment]
b/199763427

**Comment by melinath** [comment]
I think the issue here is that Terraform Validator is using the [product name](https://github.com/GoogleCloudPlatform/magic-modules/blob/21d9f76cae689ed1efd19c2079d7f49e884cf94a/mmv1/templates/validator/resource_conversion.go.erb#L25) (kms) to generate the domain; we should maybe instead be using the [GA base_url](https://github.com/GoogleCloudPlatform/magic-modules/blob/21d9f76cae689ed1efd19c2079d7f49e884cf94a/mmv1/products/kms/api.yaml#L20).

We should fix this for IAM as well as for resources.
