### ISSUE TITLE
Output converted resources at debug level during validation

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#269]
`terraform-validator convert` is primarily used as a tool for debugging issues during validation. It may be possible for us to eliminate the need for it by instead outputting the full list of converted resources to stderr at debug level during validation.

Even if we do keep the convert command around, it would still be useful for debugging for folks to have access to this information.

**Comment by melinath** [comment]
Depends on https://github.com/GoogleCloudPlatform/terraform-validator/issues/255

**Comment by morgante** [comment]
We should not remove the `convert` command. In addition to being useful for debugging, it's very helpful for dumping output to write new Constraint Templates again.

**Comment by marktru** [comment]
Internal issue: [b/211903831](b/211903831)

**Comment by melinath** [comment]
Closing this issue; no longer relevant.
