### ISSUE TITLE
Bundle dependency licenses and source code with binaries

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#272]
We want to bundle dependency licenses and source code (as required) with released binaries. This requires switching to a tarball for distribution instead of just a binary.

As part of this change, we're going to switch to the following naming convention instead of the current one:

```
terraform-validator_[PLATFORM]_[ARCH]-[VERSION].tar.gz
```

...where:

- PLATFORM is linux, darwin, or windows
- ARCH is `amd64` or `arm`
- VERSION is the semantic version without a `v` prefix, e.g. 0.1.0

The tarball will be flat and contain the following files:

- the binary (as `terraform-validator`)
- the source code & licenses (as a zip file)

**Comment by ScottSuarez** [comment]
> (as required) 
Is there a reference for this ?

**Comment by melinath** [comment]
@ScottSuarez I'll send you some information - to be more clear I probably should have said "if required by a project's license" instead of "as required"

**Comment by ScottSuarez** [comment]
I would be inclined to package the binary this way only if it is strictly required. I think this packaging method is fairly inconvenient so I would like to understand which packages have these prerequisites.   

> I'll send you some information

sounds good
