### ISSUE TITLE
Add google_organization_policy and google_folder_organization_policy resources support

### ISSUE THREAD

**Issue by jralmaraz** [GoogleCloudPlatform/terraform-validator#280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### New or Affected Resource(s)

* google_folder_organization_policy - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_folder_organization_policy

* google_organization_policy - https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_organization_policy

### Terraform-google-conversion support?

- google_organization_policy may be ? Is this the same as https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/project_organization_policy.go ?

- google_folder_organization_policy doesn't seem to be available in terraform-google-conversion.

### References

* Internal issue: [b/211906332](http://b/211906332)

**Comment by melinath** [comment]
It looks like there are three separate terraform resources:

- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_organization_policy
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_folder_organization_policy
- https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_organization_policy

Terraform Validator currently only supports the last one. It may be possible to support the non-project versions, with the caveat that we would need workarounds similar to what we have on the organization and folder resources.

**Comment by jralmaraz** [comment]
Thanks for the feedback @melinath. If I want to help contributing on this, where would you recommend me to start from ? Its my first issue and I'll start going through the contributors docs, just in case there are some hints :)

**Comment by melinath** [comment]
@jralmaraz Thanks for your interest in contributing! That doc is a little out of date (but mostly correct). Mappers.go is now part of terraform-google-conversion: https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/mappers.go

And is generated from magic-modules: https://github.com/GoogleCloudPlatform/magic-modules/blob/master/mmv1/templates/validator/mappers/mappers.go.erb

These would probably be handwritten resources.
