### ISSUE TITLE
Add support for resources

### ISSUE THREAD

**Issue by jralmaraz** [GoogleCloudPlatform/terraform-validator#284]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

**Please, let me know if it is ok to bundle the resources support request in one issue only or if I should open one per resource.**

Add support for the following terraform resources below.

### New or Affected Resource(s)

* google_cloudfunctions_function (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudfunctions_function) 

* google_folder (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_folder)

* google_organization_iam_custom_role (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_organization_iam_custom_role) 

* google_redis_instance (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/redis_instance)

* google_sql_database (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database)

* google_sql_user (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_user)

* google_kms_crypto_key_iam_policy (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_kms_crypto_key_iam#google_kms_crypto_key_iam_policy)

* google_kms_crypto_key_iam_binding (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_kms_crypto_key_iam#google_kms_crypto_key_iam_binding)

* google_kms_crypto_key_iam_member (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_kms_crypto_key_iam#google_kms_crypto_key_iam_member) 

### Terraform-google-conversion support?

* google_cloudfunctions_function seems to be supported (please confirm): https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/cloudfunctions_function.go

* google_folder doesn't seem to be supported yet.

* google_organization_iam_custom_role doesn't seem to be supported by conversion yet.

* google_redis_instance seems to be available at: https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/redis_instance.go

* google_sql_database seems to be available at: https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/sql_database.go

* google_sql_user doesn't seem to be supported by conversion yet.

* google_kms_crypto_key_iam_policy, google_kms_crypto_key_iam_binding, google_kms_crypto_key_iam_member not sure if it covers all of them under the same kms_crypto_key_iam: https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/master/google/kms_crypto_key_iam.go

### References

* #0000

**Comment by melinath** [comment]
Hi! It would be great to have this split out as one issue per resource, and if you make PRs it would be great to also have those be one per resource.
