### ISSUE TITLE
Naming standard for release binaries are not consistent 

### ISSUE THREAD

**Issue by devopsvj** [GoogleCloudPlatform/terraform-validator#288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

Naming standard for release binaries are not consistent between releases.
-  v0.1.0 to v0.5.1 has some standard in filenames and folders 
- but v0.6.0 does not follow the above standard ,  has tar and filename has version without prefix.

### New or Affected Resource(s)

N/A

### Terraform-google-conversion support?
N/A 

- [google_XXXXX is in terraform-google-conversion](https://github.com/GoogleCloudPlatform/terraform-google-conversion/tree/master/google)
- google_YYYYY is not

### References

* #0000

**Comment by melinath** [comment]
Thanks for opening an issue! This was a change in the v0.6.0 release - see https://github.com/GoogleCloudPlatform/terraform-validator/releases/tag/v0.6.0 for details. Going forward, releases will be a tarball (which contains the version in its name) which contain an executable called `terraform-validator`.
