### ISSUE TITLE
deleting a storage bucket IAM policy fails without a --project specified

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Terraform Validator version

terraform-validator: v0.6.0

### Affected Resource(s)

* google_storage_bucket_iam_*

### Expected Behavior
Deleting a storage bucket IAM policy and validate the change without specifying a project should work.

### Actual Behavior
This fails with an error that project is not set.

### Steps to Reproduce

1. Set up a terraform plan that deletes a storage bucket IAM policy.
2. `terraform-validator convert tfplan.json`

### Important Factoids

Note: this happens because the delete step happens first (and the related project is not available at that time.)

### Related Issues

Internal issue: [b/211907052](http://b/211907052)

**Comment by melinath** [comment]
This was initially a thing I brought up here: https://github.com/GoogleCloudPlatform/terraform-validator/issues/206#issuecomment-807042030 I think the change suggested in that comment might be a fix but also it might not be the right or quickest fix; we shouldn't necessarily tie the two together.

**Comment by melinath** [comment]
This is especially confusing because the [documentation states that project is an available field on storage bucket IAM](https://github.com/hashicorp/terraform-provider-google/issues/7170) (it's not) so users bounce back and forth trying different solutions, but none of them work. See b/169953815.

**Comment by iyabchen** [comment]
https://github.com/GoogleCloudPlatform/terraform-validator/pull/778
This is merged to main, and it should not require a project now for bucket resources.
