### ISSUE TITLE
Use Magic Modules as the source of truth for existing tests

### ISSUE THREAD

**Issue by melinath** [GoogleCloudPlatform/terraform-validator#332]
We want to include our existing tests in MMv1 and have them generated to the downstream to allow integration tests runs (including changes) during MMv1 PR review.

### Related issues

* Internal issue: [b/211907772](http://b/211907772)

**Comment by ScottSuarez** [comment]
steps

- [ ] Add tests to magic modules repository... add copy step to copy these tests during tfv creation
- [ ] Auto add tests to test index (so they run)
- [ ] Run integration tests within mmv1

**Comment by ScottSuarez** [comment]
this is already completed

**Comment by ScottSuarez** [comment]
ref : https://github.com/GoogleCloudPlatform/magic-modules/pull/5498
