### ISSUE TITLE
Error regarding: adding resource create/update/no-op fetching asset: lacking read permissions

### ISSUE THREAD

**Issue by ranjitk-burwood** [GoogleCloudPlatform/terraform-validator#393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Terraform Validator version

terraform-validator: v0.9.1

### Affected Resource(s)

Unsure of which resource is affected, if any.

### Terraform Plan JSON

I can provide this if it is needed to further troubleshoot.

### Debug Output

https://gist.github.com/ranjitk-burwood/c8ae50b253e0e2443554cf7a2a5a212f

### Expected Behavior

I expected terraform-validator to validate a .json file.

### Actual Behavior

I am receiving an error about insufficient read permissions. My Cloud Build service account has Project IAM Admin at the Organization level and should have the necessary IAM permissions for resourcemanager.projects.get and resourcemanager.project.getIamPolicy.

1. `terraform plan -out=tfplan.tfplan`
2. `terraform show -json tfplan.tfplan > tfplan.json`
3. `terraform-validator validate tfplan.json --policy-path=<POLICY_PATH>`

### Important Factoids

This is being run in a Cloud Build pipeline that only runs up to a `terraform plan`. There is no current infrastructure or state file present for the new code that I am using terraform-validator to scan against.

I have created terraform-validator as a Docker image and it is being pulled into the Cloud Build pipeline run from a private Artifact Registry repository.

**Comment by melinath** [comment]
@ranjitk-burwood Hi! We should be able to have someone take a look at this in the next few days. Are you able to run terraform-validator with `--verbosity=debug`? That may provide additional information that helps us assist with debugging.

**Comment by ndmckinley** [comment]
The bug seems pretty clear to me - GCP sometimes returns 403s instead of 404s to defeat dictionary attacks on globally namespaced resources - like projects - and the logs show initialization of the resource manager API which is normally used for projects.  I bet that the plan includes a project that doesn't exist, and the validator can't deal with a 403 being returned instead of a 404, and assumes it means what a 403 _usually_ means, which is that there's a permissions issue.  Seems fixable.

**Comment by ndmckinley** [comment]
@melinath Is returning the correct error message going to help here?  I am not sure if that gets our users the actual ability to validate resources that don't exist yet.

**Comment by melinath** [comment]
@ndmckinley let's discuss on the PR

**Comment by melinath** [comment]
@ranjitk-burwood are you able to confirm that the project doesn't exist yet?

**Comment by ndmckinley** [comment]
> There is no current infrastructure or state file present for the new code that I am using terraform-validator to scan against.

Seems so.

**Comment by melinath** [comment]
🤦  Thanks @ndmckinley

**Comment by ranjitk-burwood** [comment]
> @ranjitk-burwood Hi! We should be able to have someone take a look at this in the next few days. Are you able to run terraform-validator with `--verbosity=debug`? That may provide additional information that helps us assist with debugging.

Sorry for the late reply. Here is the link for `--verbosity=debug`.

https://gist.github.com/ranjitk-burwood/4390d963178bb7052a6489ff1d2c5de1

**Comment by ranjitk-burwood** [comment]
> @ranjitk-burwood are you able to confirm that the project doesn't exist yet?

Correct, there is no infrastructure or base project provisioned at the moment.

Ideally what I was looking to do was to have a `terraform plan` CloudBuild pipeline that used terraform-validator as a final step to confirm that no defined user policies were violated. This would run off a feature branch that could then be merged into master with an approved PR. In master I would setup a `terraform apply` pipeline that would provision out the necessary infrastructure.

**Comment by melinath** [comment]
Thanks to @ndmckinley we now have a good idea of what the issue is; it's now being handed off to @ScottSuarez for next steps. (More details on the PR.)

**Comment by dspeck1** [comment]
Checking in on update for this.  Is terraform-validator not designed to run against terraform plan output only (and need already deployed resources)?

**Comment by melinath** [comment]
@dspeck1 Terraform Validator is expected to run against terraform plan output; it does not need already deployed resources. The behavior described in this issue is a bug.

In this particular case, I believe that you could workaround the bug by creating the project first, then adding the IAM policy afterwards.
