### ISSUE TITLE
Allow adding support for resources not supported by CAI

### ISSUE THREAD

**Issue by ankurdua** [GoogleCloudPlatform/terraform-validator#398]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Description

We would like to use terraform validator for extracting list of resources from terraform plan files. Currently validator is not accepting addition of resources that do not have CAI support (more details in https://github.com/GoogleCloudPlatform/terraform-validator/pull/379#issuecomment-974337696) but we have need for such resources. Since CAI does not support every GA GCP resource out there and having support in CAI is not technically a requirement for adding support in validator, it would be great if this constraint is relaxed. We should ideally be able to use every resource supported by terraform google provider with terraform validator. 

### References

https://github.com/GoogleCloudPlatform/terraform-validator/pull/379

**Comment by melinath** [comment]
This constraint has been relaxed.
