### ISSUE TITLE
TFV version output incorrect

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/terraform-validator#488]
I noticed that the tfv version output seems to be `dev` as opposed to semver for some of the latest releases.  I tried a few of the latest 0.12.x.

```
terraform-validator  version
Build version: dev
```

I checked 0.11.0 which worked as expected.
```
./terraform-validator  version
Build version: v0.11.0
```

**Comment by melinath** [comment]
yeah, that makes sense. It looks like I forgot to update the build var in the release script when I moved the build version to https://github.com/GoogleCloudPlatform/terraform-validator/blob/main/version/version.go.

We should:

1. Fix this in release scripts
2. Possible find a way to test this?
3. Rebuild the impacted releases
