### ISSUE TITLE
Fix asset.resource.parent for top-level resources

### ISSUE THREAD

**Issue by nstogner** [GoogleCloudPlatform/terraform-validator#5]
Currently `asset.resource.parent` assumes the resource lives within a project. This does not work for folders, etc.

**Comment by nstogner** [comment]
Strategy: Move the calculation parent upstream into the conversions library. See GoogleCloudPlatform/magic-modules#1620.

**Comment by melinath** [comment]
Closing due to lack of detail. If you'd like to add some detail, please open a new issue! This may also be a duplicate of https://github.com/GoogleCloudPlatform/terraform-validator/issues/206
