### ISSUE TITLE
Projects with unknown ids are "replaced" with default

### ISSUE THREAD

**Issue by AdrienWalkowiak** [GoogleCloudPlatform/terraform-validator#50]
Hi,

whenever projects in my templates raise violations from my constraint, their names are wrongly set to the Provider project (--project option). It also appears that if I have more than one project in violation, I only get one project violating in the output. 

This seems to be a terraform-validator issue, as this works well with the Forseti config_validator scanner.

**Comment by melinath** [comment]
I believe the issue here is that projects with an unknown project_id (for example, due to a random ID) and all their descendants will be validated using the default project's ancestry. Please let me know if that's not the case!

This may be possible to improve but it's not a simple fix.

**Comment by melinath** [comment]
Marking this as resolved since users can now choose to not set a `--project` and have the ancestry be computed as "unknown" instead of using an incorrect project.
