### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by AdrienWalkowiak** [GoogleCloudPlatform/terraform-validator#51]
This might be something odd with my setup, but running terraform-validator version returns:

Build version:

It looks like this is not properly propagated during the install.

**Comment by t12g** [comment]
It should be fixed in the latest version.
```
$ gsutil cp gs://terraform-validator/releases/2019-06-19/terraform-validator-linux-amd64 .
$ chmod +x ./terraform-validator-linux-amd64
$ ./terraform-validator-linux-amd64  version
Build version: 2019-06-19
```
