### ISSUE TITLE
Adding IAM permissions to a project causes 404 error before project is created

### ISSUE THREAD

**Issue by DaveButland** [GoogleCloudPlatform/terraform-validator#511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave _+1_ or _me too_ comments; they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.
* If the issue is assigned to a user, that user is claiming responsibility for the issue.

### Terraform Validator version

terraform-validator: v0.12.5

### Affected Resource(s)

* google_project_iam_member

### Terraform Plan JSON

https://gist.github.com/DaveButland/88c150967215b9050e3ff84f367eb272

### Debug Output

https://gist.github.com/DaveButland/f6c1078137fb6b06835def5f7e7f3bed

### Expected Behavior

I expected the terraform-validator to validate the terraform with no violations

### Actual Behavior

The terraform-validator failed with the following response 

adding resource create/update/no-op fetching asset: Error retrieving IAM policy for project \"\": googleapi: got HTTP response code 404

### Steps to Reproduce

terraform plan -out=tfplan.tfplan
terraform show -json tfplan.tfplan > tfplan.json
terraform-validator validate tfplan.json --policy-path=<POLICY_PATH>

### Important Factoids

I have run this in cloudbuild and locally against both 0.11.0 and 0.12.5 versions of terraform-validator and get the same results. The cloudbuild service account and local user accounts have both been over privileged to rule out any IAM permission issues. 

It looks like terraform-validator is failing because it can't pull the IAM policy from the project that doesn't exist yet. If you remove the google_project_iam_member statement then the validator works correctly. 

### References

Internal Link: [http://b/218368396](http://b/218368396)

**Comment by iyabchen** [comment]
Hi @DaveButland , I am afraid the `Terraform Plan JSON` that you pasted has some syntax error, is it possible that you paste the .tf file too?

**Comment by iyabchen** [comment]
Hi @DaveButland, I guess it's because your `project` field in `google_project_iam_member` is referencing `google_project.main`. If you change the field to a project id, then it should work.

**Comment by DaveButland** [comment]
I've no idea why the json has an error in it, it was produced from the plan and just cut and pasted. The terraform is below, it is very straightforward. 

`variable "billing_account" {
  default = "XXXXX-XXXXX-XXXXX-XXXXX"
}

variable "org_id" {
  default = 1234567890
}

module "test_valid" {
  source                      = "terraform-google-modules/project-factory/google"
  version                     = "~> 11.1.1"
  random_project_id           = "true"
  default_service_account     = "deprivilege"
  name                        = "test-valid"
  org_id                      = var.org_id
  billing_account             = var.billing_account
  disable_services_on_destroy = false
  activate_apis               = []
}

resource "google_project_iam_member" "test-valid-owner" {
  project = module.test_valid.project_id
  role    = "roles/owner"
  member  = "user:test-valid@domain.com"
}
`

The reason that the project in the google_project_iam_member references the project is because the value isn't know until after the apply. This is using the terraform-google-modules/project-factory/google module and a random suffix. 

I believe this is related to #316. This only fails if the project doesn't exist yet. Once the project exists the google_project_iam_member can be added and works.

**Comment by iyabchen** [comment]
@DaveButland The fix is merged into main. The fix uses the command line flag --project to tell the ancestry, so you will need to provide that in order to get the conversion work. Could you have a try?

**Comment by melinath** [comment]
The fix for this is released as part of 0.13.0 - let us know if you keep having this issue!
