### ISSUE TITLE
terraform-validator fails  - converting tfplan to CAI assets: adding resource changes to converter: adding resource create/update/no-op converting asset: project: required field is not set

### ISSUE THREAD

**Issue by devopsvj** [GoogleCloudPlatform/terraform-validator#526]
### Terraform Validator version

terraform-validator: v0.9.1

### Debug Output

[validate] 2022-02-11T16:12:28.836218915Z	{"version": "v1.0.0", "error_details": {"error": "converting tfplan to CAI assets: adding resource changes to converter: adding resource create/update/no-op converting asset: project: required field is not set", "context": "github.com/GoogleCloudPlatform/terraform-validator/cmd.Execute\n\t/Users/stephenrlewis/projects/terraform-validator/cmd/root.go:110\nmain.main\n\t/Users/stephenrlewis/projects/terraform-validator/main.go:30\nruntime.main\n\t/usr/local/Cellar/go/1.16.6/libexec/src/runtime/proc.go:225"}}

**Comment by melinath** [comment]
@devopsvj Could you share more about your particular use case? Does using the `--project` flag to specify a default project solve this issue for you?

**Comment by melinath** [comment]
@robbierage79 that error indicates you're using Terraform 1.1.X, which changed the state plan format. You will need to upgrade to TFV >= [0.12.3](https://github.com/GoogleCloudPlatform/terraform-validator/releases/tag/v0.12.3)

**Comment by devopsvj** [comment]
@melinath  since we are using  a service account from CICD project to deploy env project.  even through we have provided project id in terraform code for the resource.  it still fails

**Comment by devopsvj** [comment]
@melinath  Thanks for your response.  In case of --project,  which project id needs to provided, In our case,  we are using service account from CICD project to deploy resource in dev project,  our CICD SA has required permission/role via IAM binding to deploy resources in DEV project.     Please let us know.

**Comment by melinath** [comment]
@devopsvj `--project` is a default project to use for resources that don't have one - so it should be the project where the resource is or will be deployed - in this case, it sounds like the dev project would be the correct choice.

**Comment by melinath** [comment]
Closing since it's been a while - please open a new ticket with full details if you're still experiencing this issue. Thanks!
