### ISSUE TITLE
Error: converting tfplan to CAI assets: adding resource changes to converter: adding resource create or update augmenting asset: getting resource ancestry for project prj-c-billing-logs: googleapi: Error 403: The caller does not have permission

### ISSUE THREAD

**Issue by amendezglobant** [GoogleCloudPlatform/terraform-validator#536]
I don't know what account the permission should go on and I don't know what permission it is either, I have tried with the cloudbuild account with project viewer and with the terraform account on the project.
Error:
Error: converting tfplan to CAI assets: adding resource changes to converter: adding resource create or update augmenting asset: getting resource ancestry for project prj-c-billing-logs-0843: googleapi: Error 403: The caller does not have permission

**Comment by melinath** [comment]
The permission you need is `resourcemanager.projects.get` for prj-c-billing-logs, which can be granted with the Project Viewer role. If you already have project viewer account I'd recommend making sure that your authentication is set up correctly: https://github.com/GoogleCloudPlatform/terraform-validator/blob/main/docs/user_guide.md#auth

You can also try running the command with `--verbosity=debug` to get more output, which might contain something useful.

If you're not able to resolve the issue, please let us know what terraform-validator version you're using and anything you discover that seems relevant. Thanks!

**Comment by melinath** [comment]
b/220187178

**Comment by amendezglobant** [comment]
Hello, thanks for the information, in my case I´m executing from cloud build service, with this documentation https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/1-org, in my case I have two service account with permission at level organization Project IAM Admin. 
Service Account for terraform org-terraform@prj-b-seed*****.iam.gserviceaccount.com
Service Account Cloud Build  ***********@cloudbuild.gserviceaccount.com 
Error again: 
Error: converting tfplan to CAI assets: adding resource changes to converter: adding resource create or update augmenting asset: getting resource ancestry for project prj-c-billing-logs-0843: googleapi: Error 403: The caller does not have permission

**Comment by amendezglobant** [comment]
I find the same error here.
https://github.com/terraform-google-modules/terraform-example-foundation/issues/620

**Comment by melinath** [comment]
Resolved by https://github.com/GoogleCloudPlatform/terraform-validator/pull/743
