### ISSUE TITLE
Support a single version Terraform at a time, possible via a global variable and build tricks.

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/terraform-validator#69]
go.mod requires github.com/hashicorp/terraform v0.11.11 thus blocking updates 

This is related to issue #68. In order to update the dependency terraform-providers/terraform-provider-google to the latest version, dependency on hashicorp/terraform needs to be upgraded to v0.12+. However, the code here is still using hashicorp/terraform v0.11. I tried upgraded to v0.12 and it would complaint about missing struct `terraform.Plan`, which seems to be removed from v0.12.

Without terraform-providers/terraform-provider-google be upgraded, pulling changes on GoogleCloudPlatform/terraform-google-conversion would create panic (as described in #68).

// cc @morgante @t12g

**Comment by morgante** [comment]
1. We want to update to the new terraform-conversion library (to support new resources)
2. That requires the new provider, which
3. Requires the new terraform 0.12 package

**Comment by yukinying** [comment]
What we want to make this even better is: 
1. refactor the code to respect 
  a) a global variable, 
  b) a build tag if global variable would not work
  to switch support to either Terraform >= v0.12 or < v0.12 for terraform-validator
2. provide the procedure to switch from one version to the other. The procedure needs to be straightforward.
3. make v0.12 the default supported version
