### ISSUE TITLE
Attach a user-agent field when making GCP API calls

### ISSUE THREAD

**Issue by t12g** [GoogleCloudPlatform/terraform-validator#7]
User agent will say something like "terraform-validator/version #" so that we can get an idea of usage.
Example of how this is done in Forseti:
https://github.com/GoogleCloudPlatform/forseti-security/blob/8a0ca24b724b2028d6aee5015c2f10e849eeed62/google/cloud/forseti/common/util/http_helpers.py#L34

**Comment by morgante** [comment]
Fixed by #28.
