### ISSUE TITLE
The use of `convert` should be supported by `validate`

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/terraform-validator#77]
My understanding about the `convert` command is that it would generate the CAI version of the TF plan. This is actually useful as the `convert` command perfoms ancestry discovery and the result of that is more comprehensive than the TF plan. However, `validate` command has no interface taking the result from `convert` which makes it redundant. 

Please consider extending the `validate` command to accept the result from `convert`, possibly via a flag like `--with-asset-json`.

**Comment by morgante** [comment]
Yes, I'd be happy to look at a PR which implements a command like this: `tfv validate --with-asset-json converted.json`

**Comment by melinath** [comment]
Closing this - it is unlikely that we'd want to add this functionality at this time.
