### ISSUE TITLE
Current released binary does not support  Terraform 0.12 

### ISSUE THREAD

**Issue by rjlupinek** [GoogleCloudPlatform/terraform-validator#83]
The latest binary build does not contain the fixes that allow for Terraform 0.12 plan output support:

> gs://terraform-validator/releases/2019-06-19/

Forgive me if this not the right place to reach the maintainers of that bucket.

**Comment by morgante** [comment]
Thanks, we'll get a new release out shortly.

**Comment by morgante** [comment]
I've just cut a new release:

> gs://terraform-validator/releases/2019-10-10/

**Comment by rjlupinek** [comment]
Thanks for the super fast support!  I tested and it works as expected.
