### ISSUE TITLE
folder does not get expanded in google_folder_iam_member

### ISSUE THREAD

**Issue by yukinying** [GoogleCloudPlatform/terraform-validator#86]
Step to reproduce: 

* Create a simple Terraform configuration like the one in documentation.
```
resource "google_folder" "department1" {
  display_name = "Department 1"
  parent       = "organizations/1234567"
}

resource "google_folder_iam_member" "admin" {
  folder  = "${google_folder.department1.name}"
  role    = "roles/editor"
  member  = "user:alice@gmail.com"
}
```

* run terraform plan, terraform show.
* add a debug statement around https://github.com/GoogleCloudPlatform/terraform-validator/blob/1fe01ae2fc848730682acd7c4cab7b5cb1bbc970/cmd/validate.go#L52 to print the assets
* notice that the name of the assets is in the form of `//cloudresourcemanager.googleapis.com/placeholder-qbilI01z"`

**Comment by yukinying** [comment]
Since https://github.com/GoogleCloudPlatform/terraform-google-conversion/blob/6c802a86e5c435b98efe6e08d03aaff2c680e906/google/folder_iam.go#L41 should expand the {{folder}} field, this seems like a problem on parsing {{folder}}.

I have also tested that if I replace `"${google_folder.department1.name}"` with a static value, then the expansion logic works correctly.

**Comment by yukinying** [comment]
// cc @morgante

**Comment by morgante** [comment]
Unfortunately there isn't any way for us to know the actual folder ID from the plan file, since the folder ID isn't specified until it is created.

**Comment by melinath** [comment]
Based on Morgante's comment it seems like this isn't going to be feasible - and it's not entirely clear to me what problem this was causing. If anyone is having problems due to this behavior, please open an issue with details!
