### ISSUE TITLE
Unify unit and integration tests

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/terraform-validator#91]
#88 introduced tests which are very similar to existing [integration tests](https://github.com/GoogleCloudPlatform/terraform-validator/tree/master/test).

Instead of maintaining these separately, we should:

1. Make a unified test/ folder which combines this with the existing test data
2. Provide two modes:
    - In unit test mode, it uses pre-generated plan JSON to validate the CAI conversion (like what you have in this PR)
    - In integration test mode, it uses the provided HCL to generate the plan, then proceeds to the unit tests from (1)

**Comment by yukinying** [comment]
This is now fixed.
